const GRAVE_HATE = [
"Agent of Erebos",
"Anafenza, the Foremost",
"Anafenza, the Foremost",
"Angel of Finality",
"Angel of Serenity",
"Beckon Apparition",
"Bojuka Bog",
"Burn Away",
"Carrion Beetles",
"Cemetery Reaper",
"Chainer, Dementia Master",
"Coffin Purge",
"Coffin Queen",
"Commit",
"Containment Priest",
"Conversion Chamber",
"Cranial Archive",
"Cremate",
"Crypt Creeper",
"Crypt Incursion",
"Curse of Oblivion",
"Day's Undoing",
"Deathrite Shaman",
"Decree of Annihilation",
"Diminishing Returns",
"Dimir Doppelganger",
"Drafna's Restoration",
"Dryad Militant",
"Dwell on the Past",
"Eater of the Dead",
"Ebony Charm",
"Entrails Feaster",
"Extirpate",
"Fade from Memory",
"Faerie Macabre",
"Flesh // Blood",
"Gaea's Blessing",
"Grafdigger's Cage",
"Grave Birthing",
"Grave Consequences",
"Gravestorm",
"Graveyard Shovel",
"Grip of Amnesia",
"Ground Seal",
"Guiding Spirit",
"Hallowed Moonlight",
"Headstone",
"Heap Doll",
"Hedonist's Trove",
"Honor the Fallen",
"Identity Crisis",
"Jotun Grunt",
"Jund Charm",
"Junktroller",
"Kalitas, Traitor of Ghet",
"Krosan Reclamation",
"Learn from the Past",
"Leyline of the Void",
"Loaming Shaman",
"Mardu Woe-Reaper",
"Memory's Journey",
"Merrow Bonegnawer",
"Mimic Vat",
"Mirror Golem",
"Misinformation",
"Morbid Bloom",
"Morningtide",
"Mourner's Shield",
"Nantuko Tracer",
"Necrogenesis",
"Necromancer's Covenant",
"Never",
"Nezumi Graverobber",
"Night Soil",
"Nihil Spellbomb",
"Not Forgotten",
"Noxious Revival",
"Nullmage Advocate",
"Offalsnout",
"Pharika, God of Affliction",
"Phyrexian Furnace",
"Planar Void",
"Primal Command",
"Pulsemage Advocate",
"Purify the Grave",
"Quest for Ancient Secrets",
"Rag Dealer",
"Rakdos Charm",
"Ravenous Trap",
"Reito Lantern",
"Relic of Progenitus",
"Reminisce",
"Repopulate",
"Rest in Peace",
"Rotfeaster Maggot",
"Samurai of the Pale Curtain",
"Scarab Feast",
"Scavenging Ooze",
"Scrabbling Claws",
"Serene Remembrance",
"Shaman's Trance",
"Shieldmage Advocate",
"Shred Memory",
"Skullsnatcher",
"Spellweaver Volute",
"Stonecloaker",
"Stream of Consciousness",
"Suffer the Past",
"Surgical Extraction",
"Temporal Cascade",
"The Mimeoplasm",
"Thraben Heretic",
"Thran Foundry",
"Time Reversal",
"Time Spiral",
"Timetwister",
"Tormod's Crypt",
"Undead Alchemist",
"Underworld Cerberus",
"Vessel of Endless Rest",
"Vile Rebirth",
"Void Maw",
"Watchers of the Dead",
"Web of Inertia",
"Wheel of Sun and Moon",
"Withered Wretch",
"Wrexial, the Risen Deep",
"Yixlid Jailer"
]

